version: '3.7'

services:
  appui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    image: bryllyantui
    container_name: bryllyantui
    restart: unless-stopped
    ports:
      - "4200:4200"
    depends_on:
      - express

  express:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: bryllyantserver
    container_name: bryllyantserver
    restart: unless-stopped
    ports:
      - "3456:3456"
    depends_on:
      - postgres

  postgres:
    container_name: postgres_container
    image: postgres
    build:
      context: ./postgresDocker
      dockerfile: db.Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
  private:
    driver: bridge
  public:
    driver: bridge

volumes:
    postgres:
    pgadmin: